### ISSUE TITLE
Error on render() when opening the UI

### ISSUE THREAD

**Issue by flederohr** [gizmore/gdo6#17]
```
13:54 [ip:] - Call to a member function render() on null in /usr/local/www/gdo6/GDO/UI/tpl/page.php Line 28
13:54 [ip:] - Uncaught Error: Call to a member function render() on null in /usr/local/www/gdo6/GDO/UI/tpl/page.php:28
Stack trace:
#0 /usr/local/www/gdo6/GDO/Core/GDT_Template.php(141): include()
#1 /usr/local/www/gdo6/GDO/UI/GDT_Page.php(84): GDO\Core\GDT_Template::php()
#2 /usr/local/www/gdo6/GDO/Core/GDT.php(321): GDO\UI\GDT_Page->renderCell()
#3 /usr/local/www/gdo6/GDO/Core/Debug.php(271): GDO\Core\GDT->render()
#4 /usr/local/www/gdo6/GDO/Core/Debug.php(239): GDO\Core\Debug::renderError()
#5 /usr/local/www/gdo6/GDO/Core/Debug.php(209): GDO\Core\Debug::debugException()
#6 [internal function]: GDO\Core\Debug::exception_handler()
#7 {main}
  thrown in GDO/UI/tpl/page.php line 28
```

**Comment by flederohr** [comment]
might be related to the condition in [GDO/UI/GDT_Page.php](https://github.com/gizmore/gdo6/commit/21f96e67e105489eb671eba6799f3502d12ea536#diff-bb1f1e82b8ede9a3b498110deec76dfa3289b2e85d3d68aa8d9100994cc69eb9)
```
 if (Module_Core::instance()->cfgLoadSidebars())
         {
-            foreach (ModuleLoader::instance()->getEnabledModules() as $module)
+            $this->topNav = GDT_Bar::make('topNav')->horizontal();
+            $this->leftNav= GDT_Bar::make('leftNav')->vertical();
+            $this->rightNav = GDT_Bar::make('rightNav')->vertical();
+            $this->bottomNav = GDT_Bar::make('bottomNav')->horizontal();
+            $app = Application::instance();
+            if (!$app->isInstall() && !$app->isCLI())
             {
'''

**Comment by flederohr** [comment]
``./gdoadm.sh config Core load_sidebars 1`` solved the problem
